language: php

php:
    - 7.1
    - 7.3

matrix:
    fast_finish: true

    allow_failures:
        - STANDALONE=1

    include:
        - php: "7.3"
          env:
              - STANDALONE=1

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE
        - STANDALONE=0

before_install:
    - phpenv config-add ci/travis.php.ini

install:
    - composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -v src/ tests/ --ignore='/Fixtures/'
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src/
    - if [[ $STANDALONE == 1 ]] ; then vendor/bin/codecept run --env isolated --coverage-xml ; fi

after_success:
    - vendor/bin/coveralls -vvv

notifications:
    email: false
