language: php

sudo: false

php:
    - 7.1
    - 7.3

env:
    global:
        - DEFAULT=1 CI=1

matrix:
    include:
        - php: 7.1
          env: PREFER_LOWEST=1

        - php: 7.3
          env: CHECKS=1 DEFAULT=0

fast_finish: true

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE
        -
before_script:
    - phpenv config-add ci/travis.php.ini
    - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction; fi;
    - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --no-interaction --prefer-dist --prefer-stable ; fi;

script:
    - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run -x Communication --coverage-xml ; fi
    - if [[ $CHECKS == 1 ]]; then composer phpstan ; fi
    - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

notifications:
    email: false

after_success:
    - travis_retry php vendor/bin/coveralls
