language: php

php:
    - 7.1
    - 7.3

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-add ci/travis.php.ini

install:
    - composer install --no-interaction --prefer-dist
    - mkdir ./config/Shared
    - cp ci/stores.php ./config/Shared/stores.php

script:
    - vendor/bin/phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml -v src/ tests/ --ignore='/Fixtures/'
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src/
    - vendor/bin/codecept run --env isolated --coverage-xml

after_success:
    - vendor/bin/coveralls -vvv

notifications:
    email: false
