language: php

php:
    - 7.1
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - phpenv config-add ci/travis.php.ini
    - phpenv config-rm xdebug.ini
    - composer global require hirak/prestissimo

install:
    - composer install --no-interaction --prefer-dist

script:
    - composer cs-check

notifications:
    email: false
