language: php

php:
    - 7.2
    - 7.4

env:
    global:
        - APPLICATION_ENV=development
        - APPLICATION_STORE=DE

before_install:
    - if [[ ${TRAVIS_PHP_VERSION} != "7.4" ]]; then phpenv config-rm xdebug.ini; fi
    - phpenv config-add ci/travis.php.ini
    - composer global require hirak/prestissimo

install:
    - composer install --no-interaction --prefer-dist

script:
    - composer cs-check
    - find ./src -path src -prune -o -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
